### PR TITLE
Add Python 3.12 to test matrix.

### PR DESCRIPTION
**Pull request by qkaiser**
See #666

### CODE REVIEW

**Comment by vlaci** [comment]
`pyyaml==6.0.1` works

**Comment by qkaiser** [comment]
[this](https://github.com/onekey-sec/unblob/actions/runs/6507126837/job/17673951089?pr=667#step:5:27) is a cache issue. I don't know how we can clean all caches on workers.

Locally I had to nuke `~/.cache/pypoetry` to make it work. See also https://pythontest.com/posts/2023/2023-10-02-py312-impimporter/

**Comment by vlaci** [comment]
> [this](https://github.com/onekey-sec/unblob/actions/runs/6507126837/job/17673951089?pr=667#step:5:27) is a cache issue. I don't know how we can clean all caches on workers.
> 
> Locally I had to nuke `~/.cache/pypoetry` to make it work. See also https://pythontest.com/posts/2023/2023-10-02-py312-impimporter/

Caches can be managed [here](https://github.com/onekey-sec/unblob/actions/caches), although we should also change caching to use version specific keys :thinking:

**Comment by qkaiser** [comment]
not a cache issue actually, I'm getting the same error locally

**Comment by qkaiser** [comment]
Not sure if my last commit is backward compatible, let's see.

**Review by vlaci — APPROVED** [review]

**Pull request merged**
