### PR TITLE
Allow carving only

### PR DESCRIPTION
**Pull request by dorpvom**
- Added command line option
- Applied early exit before extraction (@martonilles)

### CODE REVIEW

**Comment by dorpvom** [comment]
Regarding depth:

Yes, using this obviously enforces depth = 1. I would add a logger.debug for this as it is trivial when understanding the option. It would also be possible to make it a warning if depth is not the default, and one can assume it was changed on purpose.
I would probably put that into the `cli` method in _unblob/cli.py_, but I'm happy for suggestions.

**Comment by vlaci** [comment]
Thanks for sending this PR!
I see that you already had some discussion with the guys in #486 about this feature. I am sure they'll look at it as soon as they are able.

**Comment by QKaiser** [comment]
@dorpvom could you clean up your commit history and provide a single commit ? I see changes within the same code blocks in `processing.py` from both a87578963ef25095d2bce0ba4247c7dedb0e1a74 and f5a94902baddcabc8b8a5ecaab26c8882dfaba35. Also d658210f1e7f17cf6f9e45125005335fd355e7ee should not be there.

We recommend using [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716), yours could be `feat: add carve-only capability with corresponding command line switch (-s)`. Do not hesitate to provide a detailed explanation of what you did within the commit message body, this is how we document things.

**Comment by dorpvom** [comment]
> @dorpvom could you clean up your commit history and provide a single commit ? I see changes within the same code blocks in `processing.py` from both [a875789](https://github.com/onekey-sec/unblob/commit/a87578963ef25095d2bce0ba4247c7dedb0e1a74) and [f5a9490](https://github.com/onekey-sec/unblob/commit/f5a94902baddcabc8b8a5ecaab26c8882dfaba35). Also [d658210](https://github.com/onekey-sec/unblob/commit/d658210f1e7f17cf6f9e45125005335fd355e7ee) should not be there.
> 
> We recommend using [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716), yours could be `feat: add carve-only capability with corresponding command line switch (-s)`. Do not hesitate to provide a detailed explanation of what you did within the commit message body, this is how we document things.

@QKaiser So I'm not usually in bed with rebasing and force-pushing but I guess I got this history where you want it. Any additional requests?

**Review by QKaiser — APPROVED** [review]

**Pull request merged**
